---
title: "R Notebook"
output: html_notebook_OVERALL
---

## Calling necessary packages
```{r}
library(DescTools)
library(dplyr)
library(caret)
library(ggplot2)
library(tree)
library(randomForest)
library(purrr)
library(factoextra)
library(readr)
library(ggExtra)
library(tidyverse)
library(tidytext)
library(widyr)
library(igraph)
library(ggraph)
install.packages("hrbrthemes")
library(hrbrthemes)
```

# Read data file pima2.csv from your working directory 
```{r}
STAR <- read.csv("STARSCORING.csv", na.strings = c("", " "), as.is= T)

str(STAR)
```

#Multiple Regression
```{r}
summary(lm( STAR$Overall_scores
 ~ Star_rating
+ Operations_Overall_Operations_Points_Earned
+ Operations_Overall_Operations_Available_Points
+ Operations_Energy_Points_Earned
+ Operations_Building_Energy_Consumption_Points_Earned
+ Operations_Clean_and_Renewable_Energy_Points_Earned
+ Academics_Curriculum_Score_Points_Earned
+ Academics_Curriculum_Score_Available_Points
+ Academics_Academic_Courses_Points_Earned
+ Academics_Academic_Courses_Available_Points
+ Academics_Learning_Outcomes_Points_Earned
+ Academics_Learning_Outcomes_Available_Points
+ Academics_Research_Points_Earned
+ Academics_Research_Available_Points
+ Academics_Research_and_Scholarship_Points_Earned
+ Academics_Research_and_Scholarship_Available_Points
+ Engagement_Campus_Engagement_Points_Earned
+ Engagement_Campus_Engagement_Available_Points
+ Engagement_Student_Educators_Program_Points_Earned
+ Engagement_Student_Educators_Program_Available_Points
+ Engagement_Student_Life_Points_Earned
+ Engagement_Student_Life_Available_Points
+ Engagement_Employee_Educators_Program_Points_Earned
+ Engagement_Employee_Educators_Program_Available_Points
+ Engagement_Public_Engagement_Points_Earned
+ Engagement_Public_Engagement_Available_Points
+ Engagement_Community_Partnerships_Points_Earned
+ Engagement_Community_Partnerships_Available_Points
+ Engagement_InterCampus_Collaboration_Points_Earned
+ Engagement_InterCampus_Collaboration_Available_Points
+ Planning_and_Administration_Coordination_Planning_Points_Earned
+ Planning_and_Administration_Coordination_Planning_Available_Points
+ Planning_and_Administration_Sustainability_Coordination_Points_Earned
+ Planning_and_Administration_Sustainability_Coordination_Available_Points
+ Planning_and_Administration_Sustainability_Planning_Points_Earned
+ Planning_and_Administration_Sustainability_Planning_Available_Points
+ Planning_and_Administration_Participatory_Governance_Points_Earned
+ Planning_and_Administration_Participatory_Governance_Available_Points
+ Tuition_and_fees 

       
, data = STAR))

```

```{r}
summary(lm( STAR$Overall_scores
 ~
Operations_Overall_Operations_Points_Earned
+ Academics_Academic_Courses_Points_Earned
+ Academics_Learning_Outcomes_Points_Earned
+ Academics_Research_Points_Earned
+ Engagement_Campus_Engagement_Points_Earned
+ Engagement_Public_Engagement_Points_Earned
+ Engagement_Public_Engagement_Available_Points
+ Engagement_InterCampus_Collaboration_Points_Earned
+ Planning_and_Administration_Coordination_Planning_Points_Earned
+ Tuition_and_fees 

       
, data = STAR))

```
#VISIALIZATION
```{r}
ggplot(STAR, aes(x = , Overall_scores)) +
   geom_histogram(binwidth = 1)
```

```{r}
ggplot(STAR, aes(x = Overall_scores)) +
  geom_density(adjust = .2)
```
## 2 VARIABLES
```{r}
STAR |> 
  filter(!is.na(Star_rating)) |> 
  ggplot(aes(x = Star_rating)) +
  geom_bar() +
  coord_flip()

```

```{r}
ggplot(STAR, aes(x = Star_rating, y = Operations_Overall_Operations_Points_Earned)) +
  geom_point(alpha = .1)
 
```

## 3 VARIABLES
```{r}
ggplot(STAR, aes(x = Planning_and_Administration_Coordination_Planning_Points_Earned, y = Operations_Overall_Operations_Points_Earned, color = as.factor(Star_rating) )) +
  geom_point()
```

```{r}
ggplot(STAR, aes(x = Engagement_InterCampus_Collaboration_Points_Earned, y = Operations_Overall_Operations_Points_Earned, color = as.factor(Star_rating) )) +
  geom_point()
```

```{r}
ggplot(STAR, aes(x = Engagement_Public_Engagement_Points_Earned, y = Operations_Overall_Operations_Points_Earned, color = as.factor(Star_rating) )) +
  geom_point()
```

```{r}
ggplot(STAR, aes(x = Engagement_Campus_Engagement_Points_Earned, y = Operations_Overall_Operations_Points_Earned, color = as.factor(Star_rating) )) +
  geom_point()
```

## Academic 
```{r}
ggplot(STAR, aes(x = Academics_Research_Points_Earned, y = Operations_Overall_Operations_Points_Earned, color = as.factor(Star_rating) )) +
  geom_point()
```

```{r}
ggplot(STAR, aes(x = Academics_Learning_Outcomes_Points_Earned, y = Operations_Overall_Operations_Points_Earned, color = as.factor(Star_rating) )) +
  geom_point()
```


```{r}
ggplot(STAR, aes(x = Academics_Academic_Courses_Points_Earned, y = Operations_Overall_Operations_Points_Earned, color = as.factor(Star_rating) )) +
  geom_point()
```


```{r}
ggplot(STAR, aes(x = Operations_Overall_Operations_Points_Earned , y = Operations_Energy_Points_Earned)) +
  geom_point() +
  facet_wrap(~ Star_rating, nrow = 1)
```

```{r}
ggplot(STAR, aes(x = Operations_Overall_Operations_Points_Earned , y = Operations_Building_Energy_Consumption_Points_Earned)) +
  geom_point() +
  facet_wrap(~ Star_rating, nrow = 1)
```

```{r}
  ggplot(STAR, aes(x = Operations_Overall_Operations_Points_Earned , y = Operations_Clean_and_Renewable_Energy_Points_Earned)) +
  geom_point() + 
    geom_label(aes(label = Institution), 
    size = 1.5, 
    check_overlap = T
  )+
  facet_wrap(~ Star_rating, nrow = 1)
  

```

```{r}
  ggplot(STAR, aes(y = Operations_Overall_Operations_Points_Earned , x =Operations_Building_Energy_Consumption_Points_Earned, color = Star_rating )) +
  geom_point() + 
  
    ylab("Overall Operations") +
    xlab("Point of Building Energy Consumption") +
  facet_wrap(~ Star_rating, nrow = 1)+
     theme_ipsum() 
  
```


```{r}
# Most basic bubble plot
STAR %>%
 arrange(desc(Overall_scores)) %>%
    ggplot(aes(x=Operations_Overall_Operations_Points_Earned, y=Overall_scores, 
    size  = Tuition_and_fees , color= Star_rating )) +
    geom_point(alpha=0.25) +
     scale_size(range = c(.1, 16), name="Tuition fee") +
    theme_ipsum() 
```


```{r}



sp <- STAR %>%  
   arrange(desc(Overall_scores)) %>%
    ggplot(aes(x=Operations_Overall_Operations_Points_Earned, y=Overall_scores, 
    size  = Tuition_and_fees , color = Star_rating )) +
    geom_point(alpha=0.27) +
     scale_size(range = c(.1, 10), name="Tuition fee") +
    ylab("Overall Score") +
    xlab("Point of Overall Operation") +
     theme_ipsum() 


require("ggrepel")
sp + geom_label_repel(data = STAR %>%
                  filter(Star_rating == "Platinum"),
                        aes(label = Institution),
                         nudge_x = 0.08, nudge_y = 0.08,
                         size = 1)
ggsave("plot.png")
```

```{r}



sp <- STAR %>%  
   arrange(desc(Operations_Overall_Operations_Points_Earned)) %>%
    ggplot(aes(y=Operations_Overall_Operations_Points_Earned
, x=Operations_Energy_Points_Earned, 
    size  = Tuition_and_fees , color = Star_rating )) +
    geom_point(alpha=0.27) +
     scale_size(range = c(.1, 10), name="Tuition fee") +
    ylab("Overall Operations") +
    xlab("Operations Energy") +
     theme_ipsum() 


require("ggrepel")
sp + geom_label_repel(data = STAR %>%
                  filter(Operations_Overall_Operations_Points_Earned >=37,
                         Operations_Energy_Points_Earned >=3),
                        aes(label = Institution),
                         nudge_x = 0.08, nudge_y = 0.08,
                         size = 1)


```

```{r}



sp <- STAR %>%  
   arrange(desc(Operations_Overall_Operations_Points_Earned)) %>%
    ggplot(aes(y=Operations_Overall_Operations_Points_Earned
, x=Operations_Energy_Points_Earned, 
    size  = Tuition_and_fees , color = Star_rating )) +
    geom_point(alpha=0.27) +
     scale_size(range = c(.1, 10), name="Tuition fee") +
    ylab("Overall Operations") +
    xlab("Operations Energy") +
     theme_ipsum() 


require("ggrepel")
sp + geom_label_repel(data = STAR %>%
                  filter(Operations_Overall_Operations_Points_Earned >=37,
                         Operations_Energy_Points_Earned >=3,
                         Operations_Clean_and_Renewable_Energy_Points_Earned>=2),
                        aes(label = Institution),
                         nudge_x = 0.08, nudge_y = 0.08,
                         size = 1)


```